name: CI Pipeline

env:
  AZURE_WEBAPP_NAME: 'cajunlyrics-api'   # Set this to your application's name
  # AZURE_WEBAPP_PACKAGE_PATH: 'my-app-path'      # Set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --production

      - name: Run unit tests
        run: npm run test:coverage

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Build the project
        run: npm run build

      - name: Deploy to Azure web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cajunlyrics-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './dist'