name: CI Pipeline

env:
  AZURE_WEBAPP_NAME: 'cajunlyrics-api'   # Set this to your application's name
  # AZURE_WEBAPP_PACKAGE_PATH: 'my-app-path'      # Set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install all dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:coverage

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Build for production
        run: npm run build:prod

      - name: Install production dependencies only
        run: |
          rm -rf node_modules
          npm ci --production

      - name: Zip the build
        run: |
          zip -r ./dist.zip .

      - name: Verify build output
        run: test -f dist/main.js && echo "Build output verified."

      - name: Deploy to Azure web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cajunlyrics-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './dist.zip'

      # Install npm dependencies
      - name: Install npm dependencies
        run: |
          cd \home\site\wwwroot
          npm ci --production